# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.2.1
group=de.larsensmods.jeitrades
java_version=25

# Common
minecraft_version=26.1.2
mod_name=JEITrades
mod_author=LarsenR
mod_id=jeitrades
license=GPL3.0-only
credits=
description=JEI/REI Addon for trade information
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.71
neoforge_loader_version_range=[4,)

# Dependencies
jei_version=29.5.0.24
rei_version=26.1.819
architectury_version=20.0.5

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
